import '../Components/main-menu/main-menu.js';
import '../Components/registros-all/registros.js';
import '../Components/forms/form-recluta.js';
import '../Components/forms/form-teams.js';
import '../Components/listados/listado-reclutas.js';
import '../Components/listados/listados.js';
import '../Components/modal/modal-recluta.js'
import  '../Components/listados/listado-team.js';
import '../Components/modal/modal-team.js';